### ISSUE TITLE
Should VAE have the field `prior`?

### ISSUE THREAD

**Issue by vitskvara** [nmheim/GenerativeModels.jl#12]
If VAE is a general type for all kinds of VAEs, does it make sense for it to have a field called `prior`? It could either be a sampling function, Distributions object or basically anything if we use Wasserstein loss (e.g. a mixture). Then for every specific prior methods such as mean, var, sample etc would have to be created.

**Comment by smidl** [comment]
We have functions:
prior_mean()
prior_variance()
prior_sample()

I believe that they should cover all operations that we need right now. Elbo needs the first two, wasserstein the third.

**Comment by vitskvara** [comment]
Yes, however right now we have

```julia
prior_mean(m::VAE) = UniformScaling(0)
prior_variance(m::VAE) = I
prior_mean_var(m::VAE) = (UniformScaling(0), I)
prior_sample(m::VAE{T}) where T = randn(T, m.zsize)
```
for VAE, which is not very general. I would think that doing something like

```
prior_mean(m::VAE) = mean(m.prior)
```

where `prior` is a type of its own with defined methods makes more sense.

**Comment by smidl** [comment]
Well, N(0,I) is very standard for VAE. We need different prior for ARDVAE or Vamp, both of which I consider as a good case to define its own type.

Technically, we can design a type "pdf" and operations on those, but I suspect that we end up replicating "Distributions.jl", which I want to avoid.

**Comment by vitskvara** [comment]
Well and what about spherical VAE or Wasserstein with uniform prior? If we want to have a general VAE  with elbo/wasserstein loss, then we should also allow for arbitrary prior. It would be easy to make the default behaviour that if not specified, prior is N(0,1).

**Comment by smidl** [comment]
Spherical VAE should have its own type. Wasserstein VAE with uniform prior? Why? 
If we allow prior to be an arbitrary object defined outside of VAE, VAE would be difficult to construct and use. If you use default N(0,I), I suspect that it would be the only one in use...

**Comment by smidl** [comment]
Actually, after some thinking, I like the idea of having distributions. We could define two:
Pdf with methods mean(), variance(), mean_var() and sample()
CPdf with methods mean(cond), variance(cond), mean_var(cond) and sample(cond)
where the latter is conditional pdf and cond is the value of the conditioning variable.

We could specialize to:
Normal and CNormal, CNormalScalarVar, CNormalDiagVar
Dirac and CDirac
Mixture
FromDistribution (thin wrapper of our interface to general class of Distributions)

Then, encoder and decoder are CPdf and prior is Pdf. The behavior is defined by the choice of CNormal or CNormalScalarVar in the constructor.

I am still worried about overengineering. Because we could define product of distributions, e.g. for more complex priors. Chain rule and others can follow and we are in a mess....

On the other hand, the same would happen if we wanted to do that in VAE and it would be even bigger mess.

**Comment by nmheim** [comment]
will be done with #24
