### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by nmheim** [nmheim/GenerativeModels.jl#25]
Currently `elbo` calls `mean_var(m.encoder, x)` twice.

```julia
function elbo(m::AbstractVAE, x::AbstractArray; β=1)
    z = rand(m.encoder, x)  # here
    llh = mean(-loglikelihood(m.decoder, x, z))
    kl  = mean(kld(m.encoder, m.prior, x))  # and here
    llh + β*kl
end
```

 what should we do about this? from how I see it, it would only be possible to do avoid this by defining  KL which receives the computed mean/var from the encoder e.g. like this: `kld(m1, s1, prior)`/`kld(m1, s1, m2, s2)` or by not using a separate KL function.

**Comment by vitskvara** [comment]
I think we should add `kld(m1::AbstractArray, s1::AbstractArray, prior::(C)Gaussian)` since the other alternative is using 4 arrays as arguments which might not be unique to Gaussians - there are other distributions that might use two moments to compute their KLD. If we use `kld(m1, s1, prior)` where prior is gaussian, there is no ambiguity.

Also the sampling from encoder is probably gonna have to be different so that you only have to call `mean_var` once, something like this

```julia
function elbo(m::AbstractVAE, x::AbstractArray; β=1)
    (μ, σ2) = mean_var(m.encoder, x)
    z = rand_gaussian(μ, σ2)  
    llh = mean(-loglikelihood(m.decoder, x, z))
    kl  = mean(kld(μ, σ2, m.prior))  # and here
    llh + β*kl
end
```

**Comment by vitskvara** [comment]
I take that back - if we do this, we assume that encoder is gaussian which is something we wanted to avoid. Maybe there is no way to do this here, since by calling `mean_var` we always assume that encoder is gaussian.

**Comment by nmheim** [comment]
We decided to keep this for `AbstractVAE` as is. If you want better performance for your specific model you have to implement a specific loss function.
