### ISSUE TITLE
xlength and zlength check

### ISSUE THREAD

**Issue by smidl** [nmheim/GenerativeModels.jl#39]
We have constructors:
p = CGaussian(3, 2, Dense(2, 3))
where we do not check consistency of the arguments of xlength and mapping.

Current constructors allowed me to define: 
dec_dist = CGaussian{T,UnitVar}(nx, nz, f)
with incompatible f. Surprisingly it was possible to train it! It behaved weird only when calling loglikelihood. 

I would like to have at least some consistency checks, or automatic reading of xlength and zlength.
The Variance type can be specified manually. Now it is guessed from the network, I think it should be the other way around.

**Comment by smidl** [comment]
Hmmm, getting input and output size of a NN in flux is harder then I expected...

**Comment by nmheim** [comment]
They are already checked if you just call `CGaussian(nx,nz,f)` without any parametric types. The overloaded constructor will infer the correct varinace type

**Comment by smidl** [comment]
That is what I would prefer to change. I want to specify what variance structure of the Gaussian I want. I do not want to infer it from the size of the mapping.

Think about generalizations. If I have CMixture, I want to define what parameters are shared across components using switches. If the mappings are not compatible with my choice, I want an error message. 

As it is now, I define mapping and some heuristics will tell me what type of distribution is defines.

**Comment by nmheim** [comment]
Ok I see your point, sorry for the misunderstanding.
It would be possible to implement checks in a similar way as the variance type is inferred right now, no problem.

However, now that I am working with convolutions of n-dimensional time series in the mapping I have some  issues with that because the input size is not inferrable through the network. maybe we just have to leave this responsibility up to the user?

I have also not made up my mind on how to handle n-dimensional input timeseries in general. It would be nice to have an additional `slength` (state/observation length), but maybe there is a more general way of doing this?

**Comment by nmheim** [comment]
if we have xsize/zsize (#43) it will be easier to do the checks, but there still is the problem that we have to check if the mapping is on the GPU somehow. I have not come up with another way than checking for `CuArray`, but that means that we will depend on CuArrays.

I think it would be easier if we would just implement a manual function `check_sizes(pdf, x)` that performs the check manually...

**Comment by nmheim** [comment]
xlength/zlength will be removed all together in #36
