### ISSUE TITLE
Variance return function (former: why does softplus on variance kill my ODE optimization?)

### ISSUE THREAD

**Issue by nmheim** [nmheim/GenerativeModels.jl#4]
3019182fd3a4bd0ec1d3184f72859e6aca3c0c40

**Comment by honzabim** [comment]
Interesting... what is your sigma e?  I don't really see the reason why you should transform it via the softplus... because it is a free param that it will just learn. We use the softplus if it comes from the neural network actually. And I don't think you need the abs there either... at least that's how ARD works fine for me.

**Comment by nmheim** [comment]
hmm, I sometimes slightly negative values, which the log in the KL divergence does not like... it works with if I square it though...

**Comment by vitskvara** [comment]
One of the tricks I use with softplus is that I add a small constant so it works well with logs.

**Comment by nmheim** [comment]
Do we really want to introduce an additional argument to `var_mean`/`variance` that specifies the return function of the variance e.g. like this:
```julia
variance(p::Gaussian, varf=softplus_safe) = varf(p.σ2)
```
In that case the `rand` functions would have to adopt the same interface, as well as the loglikelihood, etc... Is there a smarter way of doing this? Setting some internal variable of the `GenerativeModels` package that can be changed?

It seems like over-engineering for such a minor thing. What is actually the reason for preferring softplus over just a square? I guess it is just common practice? In that case I will have to bite the bitter pill and search for the real reason why this is detrimental to my ODE optimization.

**Comment by smidl** [comment]
I definitely do not like additional functions as arguments to functions like variance, mean, etc.
If there is a need for different functions, I would specify them in the constructor with default choice. Or a switch. I used to store logsigma so that log(sigma) does not have to be computed. But I presume that is not much of an issue.

**Comment by smidl** [comment]
I mean constructor of CGaussian. It could be a new field in struct CGaussian, say ensure_positive()

**Comment by nmheim** [comment]
@vitskvara do you need softplus or is square fine with you?
Currently: 
https://github.com/nmheim/GenerativeModels.jl/blob/ddff8deced8f905d0e9149dd6898abbcb01736b8/src/pdfs/cmean_gaussian.jl#L52

**Comment by vitskvara** [comment]
I don't know if it makes any difference performance-wise or if any of these converge better.
